mattermost/mattermost-api-reference

- source/teams.yaml
Fix team members by ids endpoint docs.
It claims to return a map, but in the implementation it actually returns
an array. This changes the reference docs to reflect reality.
> Fix team members by ids endpoint docs.

- source/channels.yaml
The purpose of this is to make it possible to find out the roles of the members of a channel.
This will partially enable PLT-5049.
This is designed to be analogous to the Team Members By Ids API endpoint.
> API endpoint to get channel members by IDs.

- source/introduction.yaml
In the implementation, the endpoint for the websocket is `/api/v3/users/websocket` (see [source](https://github.com/mattermost/platform/blob/master/api/websocket.go#L20)). This fixes the docs to match the current implementation.
> Fix websocket endpoint path

- source/channels.yaml
New API endpoint to allow the update of ChannelMember roles. This will enable people to be promoted/demoted to Channel Admin role in the WebApp as per https://mattermost.atlassian.net/browse/PLT-5050
> PLT-5050 New API to update channel member roles.

- source/channels.yaml
- source/posts.yaml
- source/teams.yaml
- source/users.yaml
- Fixed the typo from retreived to retrieved
- Fixed Command typo in the `teams.yaml` to match the Command definition in the `definitions.yaml` 
- Added items for arrays to fix the swagger error when loading the yaml file in `http://editor.swagger.io/`
> Fixed typo and swagger errors

- source/v4/teams.yaml
This is the documentation for endpoint APIv4: GET /teams/{team_id}/members
[Github issue: 5409](https://github.com/mattermost/platform/issues/5409)
> Documentation for APIv4: GET /teams/{team_id}/members

- source/v4/teams.yaml
Documentation for APIv4: PUT /teams/{team_id}/members/{user_id}/roles
Github issue: [Mattermost/platform #5410](https://github.com/mattermost/platform/issues/5410)
> Documentation for APIv4: PUT /teams/{team_id}/members/{user_id}/roles

- source/v4/files.yaml
This is documentation for APIv4: GET /files/{file_id}/link
> Docs for API4: GET /files/{file_id}/link

- source/v3/channels.yaml
- source/v3/definitions.yaml
- source/v3/posts.yaml
This PR adds the documentation for pinned posts, according to [mattermost/platform/pull/4217](https://github.com/mattermost/platform/pull/4217).
> [WIP] PLT-4176: Add Documentation for Pinned Posts

- v4/source/channels.yaml
This is endpoint documentation for `APIv4 get /channels/{channel_id}/pinned`.
> APIv4 get /channels/{channel_id}/pinned

- v4/source/posts.yaml
This is endpoint documentation for APIv4 PUT /posts/{post_id}/patch.
> APIv4 PUT /posts/{post_id}/patch

- v4/source/posts.yaml
This is endpoint documentation for APIv4:
- `GET /posts/{post_id}/pin`
- `GET /posts/{post_id}/unpin`
> Doc for APIv4 get /posts/{post_id}/pin & unpin

- v4/source/teams.yaml
This is endpoint documentation for `APIv4 post /teams/search`.
> APIv4 post /teams/search

- v4/source/posts.yaml
This is endpoint documentation for `APIv4 GET /users/{user_id}/posts/flagged`.
> APIv4 GET /users/{user_id}/posts/flagged

- v4/source/commands.yaml
This is endpoint documentation for `APIv4 PUT /commands/{command_id}`.
> APIv4 PUT /commands/{command_id}

- v4/source/reactions.yaml
This is endpoint documentation for `APIv4 GET /posts/{post_id}/reactions`.
> APIv4 GET /posts/{post_id}/reactions

- v4/source/commands.yaml
This is endpoint documentation for `APIv4 DELETE /commands/{command_id}`.
> APIv4 DELETE /commands/{command_id}

- v4/source/users.yaml
This is endpoint documentation for `APIv4 PUT /users/{user_id}/active`.
> APIv4 PUT /users/{user_id}/active

- v4/source/reactions.yaml
This is endpoint documentation for `APIv4 POST /reactions`.
Note that this PR is issued on top of [PR#211](https://github.com/mattermost/mattermost-api-reference/pull/211). (Will just rebase and fix conflict later)
> APIv4 POST /reactions

- v4/source/reactions.yaml
This is endpoint documentation for `APIv4 DELETE /users/{user_id}/posts/{post_id}/reactions/name`.
This PR is on top of other PRs, will just rebase after accepting such PRs.
> APIv4 DELETE /users/{user_id}/posts/{post_id}/reactions/name

- v4/source/users.yaml
This is needed for getting any users that have been at mentioned in a post that are not already loaded by the client
> PLT-4457 Added API to get multiple users by their usernames

- v4/source/status.yaml
It looks like there is a typo in `status.yaml`. At least, my yaml parser was failing and it looks like in other files the paths are always indented 2 spaces and this one wasn't. This fixes that.
> status.yaml: indent path

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/jobs.yaml
These are the first APIs needed for the job server. As far as we have designed right now, these are the only APIs needed specifically for the job server as configuration changes will be handled by modifying config.json through existing routes.
https://mattermost.atlassian.net/browse/PLT-6408
> PLT-4608 Added APIs for querying job status

- v4/source/channels.yaml
The ChannelByName (https://github.com/mattermost/platform/blob/master/api4/api.go#L40) and ChannelByNameAndTeamName (https://github.com/mattermost/platform/blob/master/api4/api.go#L41) API calls have the `name` as part of the path signature, it is currently missing from the documentation.
> Fix ChannelAPI doc (channel by name)

- v4/source/teams.yaml
This helps fix PLT-7025 while also leaving the opportunity open to send back more structured data in future without breaking backwards compatibility.
@crspeller @jwilander what do you think of a) this returning JSON and b) the property name `results`?
> PLT-7025: Team Import API should return JSON, not attachment.

- v4/source/emoji.yaml
I'm testing this API via cURL (Server version: v4.1).
I first sent:
```
$ curl -i -H 'Authorization: Bearer <TOKEN>' -F "files=@<IMAGE>.png;type=image/png" -F "emoji={\"name\":\"<NAME>\"}" https://mattermost.iggg.org/api/v4/emoji
```
The server respond `{"id":"model.emoji.user_id.app_error","message":"model.emoji.user_id.app_error","detailed_error":"","request_id":"<REQUEST_ID>","status_code":500}`.
If we add emoji correctly, we should be send:
```
curl -i -H 'Authorization: Bearer <TOKEN>' -F "image=@<IMAGE>;type=image/png" -F "emoji={\"creator_id\":\"<ID>\",\"name\":\"<NAME>\"}" https://mattermost.iggg.org/api/v4/emoji
```
> Fix emoji.yaml to run correctly

- v4/source/posts.yaml
Plural form on "team" for endpoint `/teams/{team_id}/posts/search` was missing on documentation.
> Fix posts search API endpoint

- v4/source/dataretention.yaml
- v4/source/definitions.yaml
This adds an API endpoint to get the data retention policy. The purpose is to enable the mobile apps to ask the API "What are the cutoff timestamps before which we should remove all messages/files we have cached?".
https://mattermost.atlassian.net/browse/PLT-7705
> PLT-7705: Add a data retention policy endpoint.

- v4/source/users.yaml
Adds documentation for the forthcoming server PR as part of https://github.com/mattermost/mattermost-server/issues/7583 and PLT-7794
A few points to note:
* I wasn't sure what to put for the minimum server version, so feel free to provide input there
* These endpoints currently rely on existing permissions rather than new ones
* I created 2 endpoints rather than 1 unified "update token active status" endpoint because they do different things. Disabling a token also wipes out its related sessions.
> [PLT-7794] Added user access token enable/disable endpoints

- Makefile
- v4/source/channels.yaml
1) Fixed swagger-cli version to 1.0.0
2) Updated APIv4 POST /channels/{channel_id}/members
> Fixed swagger-cli version to 1.0.0 and updated APIv4 POST /channels/{channel_id}/members

- v4/source/webhooks.yaml
This documentation complements the changes to support https://github.com/mattermost/mattermost-server/pull/8002, exposing a Username and Profile Picture configuration for incoming webhooks to override the defaults.
See https://github.com/mattermost/mattermost-server/issues/7880 for the original ticket.
> [PLT-8173] updated documentation for creating incoming webhooks

- v4/source/definitions.yaml
- v4/source/users.yaml
Adds a new endpoint `/users/tokens` to the documentation.
- [Documentation PR](https://github.com/mattermost/mattermost-api-reference/pull/318)
- [Webapp PR](https://github.com/mattermost/mattermost-webapp/pull/496)
- [Server PR](https://github.com/mattermost/mattermost-server/pull/8038)
- [Redux PR](https://github.com/mattermost/mattermost-redux/pull/356)
- [Jira](https://mattermost.atlassian.net/browse/PLT-7793)
- [Github](https://github.com/mattermost/mattermost-server/issues/7584#issuecomment-352808489)
`is_active` was missing from the definitions so I added it too.
> [PLT-7793] Added /users/tokens endpoint

- v4/source/users.yaml
Adds a new endpoint `/users/tokens/search` to the documentation.
- [Documentation PR](https://github.com/mattermost/mattermost-api-reference/pull/320)
- [Webapp PR](https://github.com/mattermost/mattermost-webapp/pull/496)
- [Server PR](https://github.com/mattermost/mattermost-server/pull/8088)
- Redux PR
- [Jira](https://mattermost.atlassian.net/browse/PLT-7793)
- [Github](https://github.com/mattermost/mattermost-server/issues/7584#issuecomment-352808489)
> [PLT-7793] Added /users/tokens/search to docs

- v4/source/introduction.yaml
Add delete_team to list of websocket events
(Note: Only added this to APIv4.)
> [PLT-8494] Add delete_team to list of websocket events

- v4/source/files.yaml
This is for the new file upload API required for the iOS share extension. Since it's documentation, it's pretty self-explanatory
https://mattermost.atlassian.net/browse/MM-9556
> MM-9556 Added documentation for new file upload route

- v4/source/definitions.yaml
the field ActiveChannel is used only on the server side, and not goes to
the API response, so removing this field from the docs
Signed-off-by: cpanato <ctadeu@gmail.com>
JIRA: https://mattermost.atlassian.net/browse/MM-9798
> [MM-9798] API v4 Documentation for Status/Get User Status does not match payload received

- v4/source/oauth.yaml
Fixes the build of master.
Jenkins is still confused though, so thinks this PR doesn't build (it does, and it fixes the error).
> Remove invalid required paramter from oauth app PUT.

- v4/source/channels.yaml
- v4/source/teams.yaml
Clarify what deleting a channel or team do (soft delete instead of a hard delete)
Ticket to disable the permanent query parameter from `DELETE /teams/{team_id}` by default https://mattermost.atlassian.net/browse/MM-9916
> Clarify what deleting a channel or team do

- v4/source/definitions.yaml
- v4/source/system.yaml
This route is needed to make fields in the system console read only when they've been set using environment variables. I'm not sure if the response schema makes sense here since the route is currently returning an object that looks like the config with `true` for settings set through environment variables with fields left out if they're not, so it looks like
```json
{
"ServiceSettings": {
"SiteURL": true
},
"EmailSettings": {
"FeedbackName": true
}
}
```
https://mattermost.atlassian.net/browse/MM-9849
> MM-9849 Added /config/environment route

- v4/source/teams.yaml
Add APIv4 to remove team icon
- `DELETE '/teams/{team_id}/image`
Server PR (merged) - https://github.com/mattermost/mattermost-server/pull/8684
Note: `make build` passed locally
> [MM-10354] Add APIv4 to remove team icon

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/schemes.yaml
This provides the basic API for CRUD of Schemes, to enable the management of them through the System Console. It forms the core of Phase 2 advanced permissions.
There will be some additional standalone API changes in subsequent PRs for setting the Scheme on Team or Channel objects.
**Ignore the build error - Jenkins is broken.**
> MM-8799: Basic Schemes API

- v4/source/users.yaml
To create a user via the API (https://api.mattermost.com/#tag/users%2Fpaths%2F~1users%2Fpost) a query parameter named `t` can be passed to specify an invitation token id.
When doing so, an HTTP 403 error code is returned as the Mattermost app configuration parameter `EnableOpenServer` is set to `false`. 
According to the call made by the Mattermost web interface to the API when creating an account via an invitation link, the query parameter's name for the invitation token id is `iid` (with a double i) instead of `t`.
> Fix invitation token id query parameter name

- v3/source/definitions.yaml
- v4/source/definitions.yaml
I've also added description fields to the v3 api, although it's already deprecated
> Add descriptions for timestamp fields

- v4/source/teams.yaml
Adds an API endpoint to manage the `scheme_admin`/`scheme_user` properties of `TeamMember` objects, as part of Advanced Permissions Phase 2.
An analogous API will be added for `ChannelMember` objects once the design of this one has been agreed.
https://mattermost.atlassian.net/browse/MM-9730
**Ignore the build failure - it's on `master` and waiting for Jenkins to be fixed before the PR fixing it can be merged**
> MM-9730: API to manage the scheme props of team members.

- v4/source/channels.yaml
Analogous API endpoint for updating the Channel Member scheme-derived roles to the one for Team Members [here](https://github.com/mattermost/mattermost-api-reference/pull/352)
> MM-9729: Update scheme roles endpoint for Channel Members.

- v4/source/system.yaml
This references the /definitions/StatusOK ref to get the usual:
```
{
"status": "string"
}
```
Note that the actual API currently returns additional fields referencing
the `ClientRequirements` struct from the configuration, but this
scheduled to be moved to a different endpoint and we're not encouraging
use of same.
> MM-10928: fix /system/ping docs

- v4/source/definitions.yaml
- v4/source/posts.yaml
To support server-side search highlighting, the server will return a list of matches along with search results like
```
// Searching for appl*
{
"posts": ...,
"order": ...,
"results": {
"postid1": ["apple", "apples"],
"postid2": ["apply"],
}
}
```
as long as the server is the required version and has Elasticsearch enabled. Eventually, we could have the server return the matched terms for all versions, but I don't think it's worth the effort to move that logic to the server for database searches at this time.
> MM-6992 Added "matches" field to post search results

- v4/source/definitions.yaml
This is for v5.0: https://github.com/mattermost/mattermost-server/pull/8762
I know the database column was deprecated but not removed..so if we should still keep this in the API doc, feel free to close this PR.
> Remove extra_update_at from Channels call

- v4/source/introduction.yaml
APIv3 deprecation has its own section in the sidebar
> Remove note about APIv4 vs APIv3

- v4/source/introduction.yaml
channel_converted, plugin_statuses_changed, plugin_enabled, plugin_disabled and role_updated were missing.
Also ordered alphabetically, so that it's easier to find/review available websocket events.
> MM-11735: Add missing websocket events to API docs

- v4/source/channels.yaml
Add a note to channel member delete endpoint, like:
> Since server version 5.3, channel member can only be deleted either from public or private channel.
Jira ticket: [MM-11593](https://mattermost.atlassian.net/browse/MM-11593)
> [MM-11593] Add a note to channel member delete endpoint

- v4/source/teams.yaml
API doesn't handle roles in this request.
Related issue: mattermost/docs#2286
> Remove roles from request body

- v4/source/channels.yaml
The `/teams/name/{team_name}/channels/name/{channel_name}` has a `include_deleted` query parameter that allows to return deleted channels too
See: https://github.com/mattermost/mattermost-api-reference/pull/398#issuecomment-426575950
> Add documentation for 'include_deleted' pt2

- v4/source/channels.yaml
The `/teams/{team_id}/channels/name/{channel_name}` has a `include_deleted` query parameter that allows to return deleted channels too
> Add documentation for "include_deleted" parameter

- v4/html/index.html
`<meta charset='utf-8'>` is required for firefox with non-US locale
```
LC_ALL="en_US.UTF-8" firefox index.html # works
LC_ALL="ko_KR.UTF-8" firefox index.html # not works
```
> Fix charset bug on Firefox browser

- v4/source/posts.yaml
I am using the Japanese version of Mattermost. 
System version is 5.4.0.
An error occurred when using the API for updating post.
↓ error body.
```
{
"id": "api.context.invalid_body_param.app_error",
"message": "リクエストボディのpost_idが存在しないか不正です",
"detailed_error": "",
"request_id": "xi3m99tt63rfxe3mipz48zzw6r",
"status_code": 400
}
```
With this fix, the id parameter has been added.
This may not be reflected in the manual.
https://github.com/mattermost/mattermost-server/commit/fdbb6de3d52a5f41f075812e3b87616685a21b9b#diff-2f7d4446bf6cc464490bf4dd04b6d97bR386
> Add post id to body of update API

- v4/source/definitions.yaml
- v4/source/reactions.yaml
Added the api doc for the new endpoint for bulk selecting reactions to posts.
Ticket - https://github.com/mattermost/mattermost-server/issues/6798
> GH-6798 added the doc for the bulk reactions endpoint

- v4/source/users.yaml
Revoke a user access token, Disablee personal access token, and Enable personal access token requires `token_id` instead of `token`.
> Fix request parameter name related to user access token

- CONTRIBUTING.md
- v4/source/roles.yaml
Fix a typo in the go example of `roles/name` and update some old links.
> Fix a typo and broken links

- v4/source/users.yaml
A critical provisioning integration was using the PUT endpoint, expecting it to work like a patch. We thought that this may make the docs a little more clear.
> Documentation update

- v4/source/status.yaml
- v4/source/teams.yaml
This PR adds the `user_id` body parameter and the `id` body parameter to the correspondant update endpoints. The rationale behind adding the parameters to the docs instead removing the need for them is consistency. Requiring the entity id in both the URL path and the request body is used in several places through the API, including the update endpoints for post, user and team.
[Related server PR](https://github.com/mattermost/mattermost-server/pull/10361)
[MM-13810](https://mattermost.atlassian.net/browse/MM-13810)
> [MM-13810] Adds user_id and team id required body parameters to the update endpoints

- v4/source/definitions.yaml
This setting was deprecated back in 4.10
> Remove deprecated LogSettings.FileFormat from config definition

- v4/source/teams.yaml
This adds the documentation for the new endpoint introduced in https://github.com/mattermost/mattermost-server/pull/10536
> [MM-13671] Add Regenerate Team InviteID Method

- v4/source/users.yaml
Adds the parameter `group_constrained` to the `/users` and `/users/search` endpoints.
https://mattermost.atlassian.net/browse/MM-14751
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/10678)
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/2692)
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/817)
- [Has mobile changes](https://github.com/mattermost/mattermost-mobile/pull/2737)
> [MM-14751] Add group_constrained to the user list and search endpoints

- v4/source/channels.yaml
The direct-channel creation requires exactly 2 user ids as parameters.
Swagger allows arrays to define the min/max number of items
> Update Direct-channel API definition

- v4/source/opengraph.yaml
`url` parameter required but it is not documented.
> Add missing parameters section to Get Open Graph Metadata API

- Makefile
- README.md
- v4/source/bots.yaml
- v4/source/introduction.yaml
- Added docs for `GET`, `POST`, `DELETE` on `/bots/{bot_user_id}/icon` route (https://github.com/mattermost/mattermost-server/pull/11423)
- Fixed `bots` section as it wasn't showing up in the final api documentation page
- Added `make run` target to run `redoc` server for local testing
- Updated README to include instructions on how to test locally
> MM-15452 - Add docs for /bots/{bot_user_id}/icon

- v4/source/posts.yaml
This was removed in https://github.com/mattermost/mattermost-server/pull/10540, but the documentation wasn't updated to reflect that
> MM-17412 Remove file_ids from update post API

- v4/source/introduction.yaml
with the new mark as unread feature, there is a new websocket event: post_unread
I haven't marked a needed version as there seems to be no such feature for an item from a list
> [MM-17754] add post_unread event to websocket

- v4/source/definitions.yaml
This PR adds the "link" type to the embed API definition, to match the changes made as part of [this server PR](https://github.com/mattermost/mattermost-server/pull/11723).
> Adds the "link" type to the embed definition

- v4/source/actions.yaml
Adds an optional field to the `model.Dialog` struct  called `introductionText` that can accept markdown formatted text.
https://github.com/mattermost/mattermost-server/pull/12029
> MM-15219 Add support for introduction text in interactive dialogs

- v4/source/introduction.yaml
I assume `WebHooks` is incorrect here, since AFAIK
they have nothing to do with the websocket here.
> fix websocket authentication wording

- v4/source/brand.yaml
- v4/source/posts.yaml
- v4/source/system.yaml
This PR will fix validation errors thrown by https://editor.swagger.io
We are using [swagger-cli](https://github.com/BigstickCarpet/swagger-cli) to validate the yaml file, but it is not able to detect those errors.
Fixes: 
https://mattermost.atlassian.net/browse/MM-20015
https://github.com/mattermost/mattermost-api-reference/issues/468
> [MM-20015] Fix validation errors

- v4/source/channels.yaml
Updates docs to indicate that this endpoint returns a list of channels and associated roles for a user on a team, not a list of members (as the URL implies).
> Get channel members = channel memberships and roles

- v4/source/channels.yaml
This documents the `search_archived` endpoint in [this PR](https://github.com/mattermost/mattermost-server/pull/12995).
> MM-19337 API docs

- v4/source/channels.yaml
PR adds documentation for the new `/privacy` endpoint which should be the only way to change a channel's type from Public to Private and back.  
Also deprecating the `/convert` endpoint and removing the `type` parameter from the `/update` docs.
> Add documentation for channel's privacy update endpoint

- v4/source/posts.yaml
This will decide whether to set the user status as online or not
when creating a post.
https://mattermost.atlassian.net/browse/MM-21356
> MM-21356: Add set_online query param

- v4/source/plugins.yaml
Add response codes 404 for operations over non existent plugins
For the case when deleting a non existent plugin it is already documented
https://github.com/mattermost/mattermost-server/pull/11631
> Doc for operations over non existent plugins

- v4/source/introduction.yaml
This PR fixes a broken link to the JavaScript Driver, since the driver file was updated from `.js` to `.ts` in [this PR](https://github.com/mattermost/mattermost-redux/pull/936/files)
N/A
> Update link to JavaScript Driver

- v4/source/users.yaml
Add PHP samples for users endpoint documentation, based on the community-built [PHP Driver](https://github.com/gnello/php-mattermost-driver).
> Add php samples for users documentation

- v4/source/bots.yaml
**Summary**
Add PHP samples for bots endpoint documentation, based on the community-built [PHP Driver](https://github.com/gnello/php-mattermost-driver).
> Add php samples for bots documentation

- v4/source/definitions.yaml
- v4/source/groups.yaml
Updated Open API reference with the changes related to https://github.com/mattermost/mattermost-server/pull/14010 work which adds support for:
1.  Enabling or disabling group mentions in System Console
2. Adding group mentions to the list of suggestions in the channel textbox
https://mattermost.atlassian.net/browse/MM-23015
Note: this needs to be checked in before https://github.com/mattermost/mattermost-server/pull/14010 for the pre-checkin validation to pass.
> MM-23015: Add OpenAPI changes for group mentions Phase 1 

- v4/source/channels.yaml
- v4/source/definitions.yaml
Adds documentation for the new endpoint to `/member_counts_by_group` added in the server PR here https://github.com/mattermost/mattermost-server/pull/14068
https://mattermost.atlassian.net/browse/MM-23264
> [MM-23264] Add documentation for channel member counts by group

- v4/source/groups.yaml
Adds a new endpoint to return all groups for a user
https://mattermost.atlassian.net/browse/MM-24694
https://github.com/mattermost/mattermost-server/pull/14443
> MM-24694: Add documentation for retrieving Groups By user id

- v4/source/teams.yaml
- v4/source/users.yaml
Add PHP samples for teams endpoint documentation, based on the community-built [PHP Driver](https://github.com/gnello/php-mattermost-driver).
> Add php samples for teams documentation 

- package-lock.json
- v4/source/commands.yaml
- v4/source/users.yaml
We fix any remaining code example using the mattermost-server/model
package to use the v5 module prefix.
Also, running npm install updated some package-lock.json entries. So fixing them.
https://mattermost.atlassian.net/browse/MM-24425
> MM-24425: Fix remaining references to non-v5 module

- v4/source/posts.yaml
If since is used, other parameters are ignored and all posts from that time
are always returned.
https://mattermost.atlassian.net/browse/MM-25293
> MM-25293: Document that since is mutually exclusive from other params

- v4/source/groups.yaml
- v4/source/users.yaml
- Also adds `in_group_id` and `in_group` to search and get users respectively
- https://mattermost.atlassian.net/browse/MM-25263
> [MM-25263] Add group stats endpoint

- v4/source/posts.yaml
It is known that the posts are actually returned from their update time
and not create time, and there can be gaps in the post order.
Although the gaps are not expected, but it is not known what will break
at this stage, so we just fix the documentation to clarify the behavior.
> MM-22417: Clarify behavior of /channels/{channel_id}/posts endpoint

- v4/source/users.yaml
The fix adds missing user_id parameter to `/users/{user_id}/typing`.
Fixes https://github.com/mattermost/mattermost-api-reference/issues/542
> Add missing user_id parameter to /users/{user_id}/typing

- v4/source/users.yaml
- Adds `roles`, `channel_roles` & `team_roles` as optional parameters to the get users endpoint
- Creates a new endpoint to get a count of users based on a set of filter options (Locked to users with manage_system permission for now)
- https://mattermost.atlassian.net/browse/MM-26574
> [MM-26574] Add role filters to user search and filtered user stats endpoint

- v4/source/posts.yaml
PR improves documentation for the `/posts/unread` endpoint by making the naming less ambiguous and explicitly defining valid values for the `limit_before` and `limit_after` query parameters.
https://mattermost.atlassian.net/browse/MM-26535
https://github.com/mattermost/mattermost-server/pull/15049
> [MM-26535] Improve docs for /posts/unread endpoint

- v4/source/definitions.yaml
- v4/source/system.yaml
PR adds documentation for the added `/integrity` local-mode API endpoint.
https://mattermost.atlassian.net/browse/MM-25652
https://github.com/mattermost/mattermost-server/pull/15033
> [MM-25652] Add documentation for /integrity local-mode API endpoint

- v4/source/jobs.yaml
Summary
Name job folders by job id rather than start and end times
Ticket Link
https://mattermost.atlassian.net/browse/MM-19640
Needed to let https://github.com/mattermost/mattermost-server/pull/14976 pass the Build CI tests
> [MM-19640] Retrieve Compliance files from the System Console

- v4/source/system.yaml
"bot_post_counts_day" query seems to work fine, but it's missing in api document.
https://github.com/mattermost/mattermost-server/blob/master/app/analytics.go#L196
There is no issue/ticket
> Add bot_post_counts_day query to /analytics/old

- v4/source/ldap.yaml
Documents new endpoint for LDAP, TLS Certificate uploading/removing
https://mattermost.atlassian.net/browse/MM-27352
https://github.com/mattermost/mattermost-webapp/pull/6345
https://github.com/mattermost/mattermost-redux/pull/1224
https://github.com/mattermost/mattermost-server/pull/15361
https://github.com/mattermost/enterprise/pull/752
> MM-27352: Add doc for ldap certificate update/delete

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/uploads.yaml
- v4/source/users.yaml
Add documentation for new upload API endpoints.
https://mattermost.atlassian.net/browse/MM-26812
https://github.com/mattermost/mattermost-server/pull/15252
> [MM-26812] Add documentation for new upload API endpoints

- v4/source/uploads.yaml
PR updates the docs for the newly added resumable uploads API endpoint to include a mention to `multipart/form-data` support.
https://mattermost.atlassian.net/browse/MM-28580
> [MM-28580] Update docs for resumable uploads API endpoint

- v4/source/bleve.yaml
- Related server PR https://github.com/mattermost/mattermost-server/pull/15557
- https://mattermost.atlassian.net/browse/MM-28537
> [MM-28537] Purge indexes should be tied to sysconsole_write_experimental

- v4/source/system.yaml
Add AdminAdvisor v2 new API method reference.
https://mattermost.atlassian.net/browse/MM-28733
redux: https://github.com/mattermost/mattermost-redux/pull/1237
webapp: https://github.com/mattermost/mattermost-webapp/pull/6461
server: https://github.com/mattermost/mattermost-server/pull/15515/files
> MM-28733: Add AdminAdvisor v2 new API method reference

- v4/source/definitions.yaml
- v4/source/system.yaml
Updated the API doc entry for `System -> Check system health` to include the `get_server_status` parameter, and response schema.
Noticed while fixing https://github.com/mattermost/mattermost-server/pull/15752
> [GH-15742] updated 'check system health' docs

- v4/source/teams.yaml
Correct permissions to invite a user by email to a team.
https://mattermost.atlassian.net/browse/MM-29279
> MM-29279: Correct permissions to invite a user by email to a team.

- Makefile
- v4/source/imports.yaml
- v4/source/introduction.yaml
PR adds documentation for the new `/imports` API endpoint.
https://mattermost.atlassian.net/browse/MM-28424
https://github.com/mattermost/mattermost-server/pull/16062
> [MM-28422] Add /imports endpoint

- v4/source/users.yaml
This reverts commit 8fd99d0477525aa686a3a27f4209ce65bb4d55f8.
> Revert "MM-30558 - updated routes for thread related APIs (#590)"

- v4/source/webhooks.yaml
Updates the documentation of create incoming and outgoing webhooks to include the user and creator ids.
https://mattermost.atlassian.net/browse/MM-30016
https://mattermost.atlassian.net/browse/MM-30021
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/16425)
> [MM-30016] Add user_id and creator_id to the webhook create endpoints

- v4/source/definitions.yaml
- v4/source/users.yaml
As per the current description, the API is only supposed to be used
to change authentication method. The password field was anyways a noop for that.
Removing that does not break anything. It can still be sent, but will remain as a noop.
https://mattermost.atlassian.net/browse/MM-32013
> MM-32013: users.yaml: update API definition to remove references to password

- v4/source/cloud.yaml
- v4/source/definitions.yaml
This PR adds a new cloud only endpoint to obtain stats about the kind of subscription a user has.
[MM-31497](https://mattermost.atlassian.net/browse/MM-31497?atlOrigin=eyJpIjoiMDJhMDQwOWM1ODZhNDMzM2IyNDE5ZjAxNDM1OTg4Y2UiLCJwIjoiaiJ9)
[https://github.com/mattermost/mattermost-server/pull/16786](https://github.com/mattermost/mattermost-server/pull/16786)
> [MM-31497] - Add spec for cloud/subscription/stats

- v4/source/exports.yaml
Bumping the MM version for the `/exports` endpoint since it didn't make it in 5.32.
> Bump version for /exports endpoint

- v4/source/cloud.yaml
This is the spec definition for the endpoint ```/api/v4/cloud/subscription/limitreached/invite``` that adds rate limited way for users to alert sysadmins to upgrade their cloud workspace
[MM-32543](https://mattermost.atlassian.net/secure/RapidBoard.jspa?rapidView=79&projectKey=MM&modal=detail&selectedIssue=MM-32543&quickFilter=382)
> [MM-32543] - Add spec for cloud/alert/admin

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/sharedchannels.yaml
This PR adds API docs for new endpoint `/sharedchannels/getremoteinfo/{remote_id}`
Note: minimum version is set to 5.50 as a placeholder as we do not yet know when shared channels will be released.
https://mattermost.atlassian.net/browse/MM-33444
Implementation: https://github.com/mattermost/mattermost-server/pull/17063
> MM-33444 API docs for getremoteinfo

- v4/source/channels.yaml
Documents the 200 member limit for `/channels/{channel_id}/members`
> Adding 200 user limit to channel members

- v4/source/definitions.yaml
Mobile team has requested that `model.SharedChannel` serialize to JSON using the same field names as other Channel objects. i.e.`GetAllSharedChannels` should have matching field names returned as `GetPublicChannels` for any fields they have in common.
This PR updates the API documentation to reflect the modified field names.
Server PR: https://github.com/mattermost/mattermost-server/pull/17634
https://mattermost.atlassian.net/browse/MM-35802
> MM-35802 Rename json fields for GetAllSharedChannels to match other channel objects

- v4/source/channels.yaml
Removing the convert channel endpoint and using `/channels/{channel_id}/privacy` instead
https://mattermost.atlassian.net/browse/MM-18391
https://github.com/mattermost/mattermost-webapp/pull/8484
https://github.com/mattermost/mattermost-server/pull/18015
> [MM-18391] Removing convert channel endpoint

- v4/source/definitions.yaml
Removing the deprecated `Posts.ParentId`.
https://mattermost.atlassian.net/browse/MM-29217
https://github.com/mattermost/mattermost-server/pull/17923
https://github.com/mattermost/enterprise/pull/1019
https://github.com/mattermost/mattermost-webapp/pull/8401
https://github.com/mattermost/mattermost-mobile/pull/5541
> [MM-29217] Remove Posts.ParentId

- v4/source/definitions.yaml
Removes the `Post.Filenames` field.
https://mattermost.atlassian.net/browse/MM-36446
https://github.com/mattermost/mattermost-server/pull/17985
> MM-36446: Deprecate Post.Fieldnames field.

- v4/source/status.yaml
- the tag custom_status was not generating the index entry in the html
but also I think that should be part of the status reference
context: https://community-daily.mattermost.com/core/pl/mw896noc3jgmfkj83gf6uipxhr
> update tag for custom status to be the same as status

- v4/source/users.yaml
The API requires a personal access token when creating accounts using auth services such as LDAP.
> Clarified create user docs for authentication

- v4/source/channels.yaml
When investigating the system console > channels we noticed a few parameters that were not included in the documentation. These are those.
The query the system console uses is `http://<<siteURL>>/api/v4/channels?page=0&per_page=10&not_associated_to_group=&exclude_default_channels=false&include_total_count=true&include_deleted=true`
> Updated channel endpoint parameters

- v4/source/channels.yaml
- v4/source/dataretention.yaml
Add missing item type to `team_ids` arrays in `SearchChannelsForRetentionPolicy` and `SearchAllChannels`. This provides a partial fix for #640
> Add missing types to array definitions in channels and dataretention

- v4/source/system.yaml
It took me a while to realize that the whole configuration should
be specified when doing a PUT (not just the fields that one wants
to change). Here is a small paragraph explaining that, hoping to
help others.
It looks like secret parameters (passwords, keys?) are automatically
replaced with strings of asterisks (`**********...`) and that these
get ignored when we PUT a new configuration, but I'm not sure.
If someone knows for sure, it would be fantastic to clarify as well.
Thanks! ♥
> Clarify how to change system configuration

- README.md
- v4/source/introduction.yaml
After the http conversation I noticed a few urls are still http in this repo. I tried to get the ones that wouldn't cause an issue and updated them here. 
The `redoc-static.html` seems like it also has a ton of urls to update, but changing those didn't feed into the output `index.html`, so i'm not exactly sure where to make that change. It has a lot of URLS like `http://www.w3.org/2000/svg` that can be changed, and some in the scripts themselves.
> Replaced http URLs with https in various places

- v4/source/emoji.yaml
This PR fixes a typo in a parameter description for the GetEmojiList operation. The parameter in question is the `per_page` parameter, which should specify the number of *emojis* per page, but instead the current API reference says *users* per page.
No ticket involved.
> update GetEmojiList's per_page to refer to emojis

- v4/source/roles.yaml
Adds an `operationId` field to the API `/roles` call, arbitrarily called `GetAllRoles` by similarity to other API endpoints (e.g. `GetAllChannels`, `GetAllTeams`, ...).
> Add operationId to /roles

- v4/source/posts.yaml
Added documentation for new 'include_deleted' query param on get file info api
Fixes https://github.com/mattermost/mattermost-server/issues/20231
https://mattermost.atlassian.net/browse/MM-42194
> [MM-42194] Added documentation for new 'include_deleted' query param on get file info api

- v4/source/definitions.yaml
Modified notify_props to include only strings in documentation, not booleans.
Fixes https://github.com/mattermost/mattermost-server/issues/19840
> [MM-42792] Modified notify_props docs to include only strings, not booleans

- v4/source/emoji.yaml
Adds file type info under create a custom emoji section (suggested [here](https://github.com/mattermost/mattermost-server/pull/20283#issuecomment-1144394169))
Fixes https://github.com/mattermost/mattermost-server/issues/20223
> Mm-20223 Add webp emoji support

- .gitpod.yml
- README.md
This PR makes it so we can use Gitpod to spin up an environment to work on the API reference docs. This should be straightforward to add to other doc repos as well
Link to test this PR with gitpod https://gitpod.io/#https://github.com/mattermost/mattermost-api-reference/pull/708
> Add gitpod.yml and put gitpod link in readme

- v4/source/webhooks.yaml
a tiny changes on misleading information on `update incoming webhook.`. There is more information on issue link below.
Fixes https://github.com/mattermost/mattermost-api-reference/issues/690
> hook_id updated as id on payload

- v4/source/posts.yaml
A new query parameter is being added to the endpoint `/api/v4/channels/{channel_id}/posts`. Deleted posts can be included as long as system admins request them.
The new query parameter is added here: https://github.com/mattermost/mattermost-server/pull/19985
[https://mattermost.atlassian.net/browse/MM-42191](https://mattermost.atlassian.net/browse/MM-42191)
> [MM-42191]: Add includeDeleted parameter

- v4/source/users.yaml
A new API to set a thread as unread is being added to the server so
that you can mark a thread as unread by post id.
The new API is added here https://github.com/mattermost/mattermost-server/pull/19951
https://mattermost.atlassian.net/browse/MM-41185
> [MM-41185]: adds reference on mark thread as unread by post

- v4/source/files.yaml
Add `First-Inaccessible-File-Time` response-403-header for getFile APIs, which indicates if files are inaccessible due to the cloud plan's limit.
JIRA - https://mattermost.atlassian.net/browse/MM-44489
Depends on this server PR - https://github.com/mattermost/mattermost-server/pull/20703
> [MM-44489] Cloud limits: enforcing files

- .gitignore
- Makefile
- README.md
- package-lock.json
- package.json
- playbooks/extract.js
- playbooks/merge-definitions.js
- playbooks/merge-tags.js
- playbooks/tags.yaml
This PR integrates the API spec for Playbooks into the Mattermost API docs. The Playbooks OpenAPI spec is downloaded from GitHub at build time, and then it is parsed, split up, and combined with the existing API specs in YAML files.
At the time of this PR posting, OpenAPI service tags are not present in the Playbooks API specs. Substitute tags are provided in the `playbooks/tags.yaml` file until tags are added to the spec.
> Add Playbook APIs to Mattermost API docs

- v4/source/definitions.yaml
- v4/source/users.yaml
The documentation of GetKnownUsers showed an integer as the result. An array of userIds is returned by this comment.
[issue](https://github.com/mattermost/mattermost-api-reference/issues/666)
> fixing output GetKnownUsers to array

- playbooks/extract.js
Update to fetch the API spec for Playbooks from the new mono-repo location.
None.
> Fetch Playbooks API from mono-repo

- README.md
Contributor notes reference previous repository structure. Links have been updated to point future contributors to the new location for playbook API documentation in mattermost-server mono-repo. 
Follow on PR to contributor guideline changes as a result of https://github.com/mattermost/mattermost-api-reference/pull/730
> Playbook API documentation reference updated to mattermost-server repo

- v4/source/definitions.yaml
The `last_post_at` field under `Channel` is a timestamp. Therefore, it should be formatted as `int64`.
EDIT: Also fixed `last_password_update` and `last_picture_update` as [suggested below](https://github.com/mattermost/mattermost-api-reference/pull/728#pullrequestreview-1437032048)
Fixes #727
> last_post_at timestamp should be int64

- v4/source/introduction.yaml
Thanks to a [community member report](https://github.com/mattermost/mattermost/pull/23345#issuecomment-1563798237) for spotting that the permalinks to our Go client stopped working with the submodule update. 
The redux link for the JavaScript driver is super old, but I'm not aware of a replacement, so I left it untouched.
None.
> updated client paths

- README.md
- playbooks/extract.js
This PR reverts https://github.com/mattermost/mattermost-api-reference/pull/730 and https://github.com/mattermost/mattermost-api-reference/pull/731, making the API fetch and reference the playbooks plugin instead of the mono repo.
https://mattermost.atlassian.net/browse/MM-53155
> Fetch playbooks api from plugin
