- source/channels.yaml
- source/definitions.yaml
- source/posts.yaml
- source/users.yaml
Proposal for API changes in mattermost/platform#4106
> API Proposal: Updated APIs for channel member refactor

- source/definitions.yaml
- source/teams.yaml
- source/users.yaml
Proposal for API changes in mattermost/platform#4159
> API Proposal: Updated APIs for team member refactor

- source/definitions.yaml
- source/users.yaml
API proposal for mattermost/platform#4239
> Add API for autocompleting users

- source/channels.yaml
I managed to add a user to a channel and was wondering if you where insterested in this documentation addentum.
> Add user to a channel

- source/users.yaml
Not so sure about the description
> Add users search api doc fix #16

- source/channels.yaml
I'm not really sure if I documented well the responses description/type
> Add channel delete

- source/channels.yaml
part of this ticket https://github.com/mattermost/platform/issues/4515
> Add API call to get a channel by its name

- source/definitions.yaml
- source/posts.yaml
Added API documentation for /get_opengraph_metadata API added in platform pull request https://github.com/mattermost/platform/pull/4890.
Related Github ticket (on platform): https://github.com/mattermost/platform/issues/4257
> mattermost/platform#4257 Added API documentation for /get_opengraph_metadata API

- source/users.yaml
fixes #20 
Documented the API endpoint `api/v3/users/reset_password` with multiple response objects. Had a bit of struggle on how to show multiple response objects using with the same response code. I placed it on the examples
> #20 - hackfest - reset user password

- Makefile
- source/admin.yaml
- source/definitions.yaml
- source/introduction.yaml
- source/posts.yaml
I added most of the admin endpoints (although the failure responses aren't fully documented for them) and a few other minor changes.
> Added admin endpoints

- Makefile
- source/v3/definitions.yaml
- source/v3/introduction.yaml
- source/v3/webhooks.yaml
Added documentation for existing API.
- references #43 
- references #45
> Added docs for list and delete outgoing webhook

- source/v4/channels.yaml
- Added docs for `GET /channels/{channel_id}`
- Added docs for `GET /teams/{team_id}/channels/name/{channel_name}`
- Added docs for `GET /teams/name/{team_name}/channels/name/{channel_name}`
> Document GET channel endpoints for APIv4

- source/v4/definitions.yaml
- source/v4/system.yaml
https://github.com/mattermost/platform/pull/5443/files/390a61c16ee916fd2e26c923f172ced447734ddd#r101585214
> Modify /system/ping Endpoint to return StatusOK

- source/v4/teams.yaml
Document api4 GET teams/{team_id}/stats
[mattermost/platform] Github issue: [#5408](https://github.com/mattermost/platform/issues/5408)
> api4 GET teams/{team_id}/stats

- source/v4/teams.yaml
Documentation for APIv4: GET /teams/name/{name}
Mattermost/platform Github issue: [#5414](https://github.com/mattermost/platform/issues/5414)
> Documentation for APIv4: GET /teams/name/{name} (reopened)

- source/v4/users.yaml
Documentation for APIv4: GET /users/{user_id}/audits
Github issue: [Mattermost/platform #5411](https://github.com/mattermost/platform/issues/5411)
> Documentation for APIv4: GET /users/{user_id}/audits

- source/v4/users.yaml
This is documentation for Docs for APIv4: GET users/{user_id}/image
> Docs for APIv4: GET users/{user_id}/image

- source/v4/definitions.yaml
- source/v4/teams.yaml
API PR: https://github.com/mattermost/platform/pull/5517
> add reference doc for Check if team exists endpoint for APIv4

- source/v3/introduction.yaml
- source/v4/introduction.yaml
This adds a channel_created websocket event to match https://github.com/mattermost/platform/pull/5548
> Add WS event for create channel

- source/v4/users.yaml
PR for the implementation: https://github.com/mattermost/platform/pull/5502
> add doc for /users/{user_id}/verify/email

- source/v4/files.yaml
This is documentation for APIv4: GET /files/{file_id}/thumbnail
> Docs for APIv4: GET /files/{file_id}/thumbnail

- Makefile
- source/v4/preferences.yaml
- source/v4/teams.yaml
- source/v4/users.yaml
- Added docs for preferences endpoints for APIv4
- Fixed Audit and TeamMember definition errors
> Added docs for preferences endpoints for APIv4

- source/v4/users.yaml
This is documentation for APIv4: POST users/{user_id}/image (also this is combined with [GET docs PR 112](https://github.com/mattermost/mattermost-api-reference/pull/112))
> Docs for APIv4: POST users/{user_id}/image (combined with PR #112)

- source/v4/files.yaml
This is documentation for APIv4: GET /files/{file_id}/preview
> Docs for APIv4: GET /files/{file_id}/preview

- source/v4/system.yaml
implementation PR: https://github.com/mattermost/platform/pull/5717
> add documentation for POST /database/recycle apiv4

- source/v4/introduction.yaml
- source/v4/system.yaml
implementation PR: https://github.com/mattermost/platform/pull/5716
> add documentation for POST /email/test

- source/v4/system.yaml
Implementation PR: https://github.com/mattermost/platform/pull/5706
> add documentation for PUT /system/config apiv4 - update config

- source/v4/system.yaml
Implementation PR: https://github.com/mattermost/platform/pull/5701
> add documentation for getConfig endpoint for apiv4

- source/v4/system.yaml
Implemention code PR: https://github.com/mattermost/platform/pull/5713
> add documentation for POST /config/reload

- source/v4/channels.yaml
This is documentation for APIv4: GET /team/{team_id}/channels
> Docs for APIv4: GET /team/{team_id}/channels

- source/v4/channels.yaml
PR for the implementation: https://github.com/mattermost/platform/pull/5624
> add doc for update channel apiv4

- source/v4/files.yaml
This is documentation for APIv4: GET /files/{file_id}/info
> Docs for APIv4: GET /files/{file_id}/info

- source/v4/teams.yaml
GET /users/{user_id}/teams/unread
> Get unread totals for all the teams a user is on.

- source/v4/channels.yaml
This is documentation for ```APIv4: DELETE /channels/{channel_id}```
> Docs for APIv4: DELETE /channels/{channel_id}

- v4/source/system.yaml
Implementation PR: https://github.com/mattermost/platform/pull/5756
> add documentation for POST /caches/invalidate endpoint for apiV4

- v4/source/webhooks.yaml
> add documentation for PUT /hooks/outgoing/{hook_id}

- v4/source/webhooks.yaml
> add documentation for /hooks/outgoing/{hook_id}/regen_token apiv4

- v4/source/channels.yaml
This is document for endpoint APIv4 POST /channels/{channel_id}/members
> Docs for APIv4 POST /channels/{channel_id}/members

- v4/source/webhooks.yaml
Implementation PR: https://github.com/mattermost/platform/pull/5827
> add documentation for GEt outgoing webhook for apiv4

- v4/source/teams.yaml
This is documentation for APIv4 put /teams/{team_id}/patch.
> APIv4 put /teams/{team_id}/patch

- Makefile
- v4/source/commands.yaml
implementation PR: https://github.com/mattermost/platform/pull/5849
> add documentation for POST /commands

- v4/source/teams.yaml
This is document for endpoint APIv4 POST /teams/{team_id}/members.
> APIv4 POST /teams/{team_id}/members

- v4/source/definitions.yaml
- v4/source/status.yaml
implementation PR: https://github.com/mattermost/platform/pull/5824
> add documentation for GET /users/{user_id}/status - user status 

- v4/source/channels.yaml
Wrong return code: 200 OK instead of 201 Created
TrivialFix
> Fix wrong return code

- v4/source/channels.yaml
This is document for endpoint APIv4 post /channels/ids.
> APIv4 post /channels/ids

- v4/source/channels.yaml
team_id is on path not query string
TrivialFix
> Fix small issue in description

- v4/source/users.yaml
API to get users not in a team.
https://mattermost.atlassian.net/browse/PLT-6083
> PLT-6083: API to get users not in a team.

- v4/source/status.yaml
implementation pr: https://github.com/mattermost/platform/pull/5894
> add documentation for POST /users/status/ids for apiv4

- v4/source/commands.yaml
implementation PR: https://github.com/mattermost/platform/pull/5865
> add documentation for GET /commands

- v4/source/status.yaml
Implementation pr: https://github.com/mattermost/platform/pull/5928
> add documentation for PUT /users/{user_id}/status

- v4/source/teams.yaml
This is endpoint documentation for `APIv4 DELETE /teams/{team_id}`.
> APIv4 DELETE /teams/{team_id}

- v4/source/users.yaml
https://mattermost.atlassian.net/browse/PLT-6162
> PLT-6162: Search users not in team.

- v4/source/teams.yaml
https://mattermost.atlassian.net/browse/PLT-6169
> PLT-6169: API for batch adding of team members.

- v4/source/teams.yaml
PR: https://github.com/mattermost/platform/pull/5944
> add documentation for POST /teams/{team_id}/invite/email

- v4/source/teams.yaml
implementation pr: https://github.com/mattermost/platform/pull/5920
> add documentation from POST /teams/{team_id}/import

- v4/source/commands.yaml
PR: https://github.com/mattermost/platform/pull/5951
> add documentation for GET /teams/{team_id}/commands/autocomplete

- v4/source/definitions.yaml
- v4/source/emoji.yaml
implementation PR: https://github.com/mattermost/platform/pull/5868
> add documentation for POST /emoji

- v4/source/emoji.yaml
implementation PR: https://github.com/mattermost/platform/pull/6007
> add documentation for GET /emoji apiv4

- v4/source/emoji.yaml
- v4/source/introduction.yaml
Code PR: https://github.com/mattermost/platform/pull/6021
> Add documentation for for GET / Delete /emoji/{emoji_id}

- v4/source/commands.yaml
code PR: https://github.com/mattermost/platform/pull/6052
> add documentation for POST /commands/{command_id}/regen_token

- v4/source/channels.yaml
This is endpoint documentation for `APIv4 POST /channels/group`.
> APIv4 POST /channels/group

- v4/source/system.yaml
PR: https://github.com/mattermost/platform/pull/6143
> add documentation for POST /logs

- v4/source/emoji.yaml
PR: https://github.com/mattermost/platform/pull/6141
> add documentation for GET /emoji/{emoji_id}/image

- v3/source/introduction.yaml
- v4/source/introduction.yaml
Add missing WebSocket events from https://github.com/mattermost/platform/blob/master/model/websocket_message.go
> Add missing WebSocket events

- v4/source/channels.yaml
Add Endpoint to fetch deleted channels
> APIv4 GET /teams/{team_id}/channels/deleted

- v4/source/opengraph.yaml
code pr: https://github.com/mattermost/platform/pull/6343
> add documentation for POST /opengraph

- v4/source/system.yaml
Code PR: https://github.com/mattermost/platform/pull/6331
> add documentation for GET /system/health

- v4/source/channels.yaml
Add Endpoint to restore deleted channels
> APIv4 POST /channels/{channel}/restore

- v4/source/commands.yaml
Remove creator_id from required fields for create command, add more fields to request sample
> Remove creator_id from required fields for command

- v4/source/commands.yaml
- v4/source/definitions.yaml
This is endpoint documentation for `APIv4 POST /commands/execute`.
> APIv4 POST /commands/execute

- v4/source/teams.yaml
Needed for https://github.com/mattermost/platform/pull/6604
> Add docs for APIv4 permanent delete

- v4/source/brand.yaml
- v4/source/system.yaml
> Update email test and brand endpoint descriptions

- v4/source/teams.yaml
> Fix method for Update a team member roles

- Makefile
- v4/source/elasticsearch.yaml
- v4/source/introduction.yaml
Admin endpoint for testing elasticsearch config.
https://mattermost.atlassian.net/browse/PLT-6474
> PLT-6474: Elasticsearch test config endpoint.

- v4/source/emoji.yaml
Also includes some minor text updates.
> Add paging documentation to GET /emoji

- v4/source/elasticsearch.yaml
Add a config in the body of elasticsearch test endpoint.
> Add config parameter to /elasticsearch/test

- v4/source/teams.yaml
See implementation: https://github.com/mattermost/platform/pull/5296
> Fixed user/{user_id}/teams return schema

- v4/source/elasticsearch.yaml
API to purge Elasticsearch indexes.
> PLT-6595: API to purge Elasticsearch indexes.

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/jobs.yaml
Proposed API for Jobs.
Needed to start on the system console UI for jobs in https://mattermost.atlassian.net/browse/PLT-6595
> PLT-6595: Jobs API.

- v4/source/introduction.yaml
> "depreaction" -> "deprecation"

- v4/source/introduction.yaml
https://mattermost.atlassian.net/browse/PLT-7380
> Add brief summary of changes from v3 to v4

- v4/source/posts.yaml
To go along with https://github.com/mattermost/platform/pull/7274
> PLT-6403: Add post action endpoint

- v4/source/system.yaml
the Ping endpoint sample is in another PR.
> [PLT-6440] add code samples for sytem api

- v4/source/oauth.yaml
Document v4 endpoint for editing OAuth apps, add GO code samples
https://github.com/mattermost/platform/issues/4752
> PLT-4752 Document v4 endpoint for editing OAuth apps

- v4/source/users.yaml
mattermost-server
mattermost-redux
mattermost-webapp
mattermost-api-reference
Adds documentation for api endpoint for revoking all sessions for a user at users/{user_id}/sessions/revoke/all
https://github.com/mattermost/mattermost-server/issues/7493
> [PLT-7396] Add the ability to revoke user sessions in System Console > Users #7493

- v4/source/system.yaml
https://mattermost.atlassian.net/browse/PLT-7532
> PLT-7532 Update permissions on POST /logs endpoint

- v4/source/channels.yaml
Copy/paste error had them under teams accidentally.
> Move some channel endpoints to be under channel section

- v4/source/channels.yaml
- v4/source/definitions.yaml
- v4/source/users.yaml
Document user and channel notification properties. Also minor text update to an unrelated endpoint.
> Document user and channel notification properties

- v4/source/introduction.yaml
https://github.com/mattermost/mattermost-server/pull/7745
Also added `memberrole_updated` which was missing.
> Doc user_role_updated WS event

- v4/source/system.yaml
Fix for [\[Help Wanted\] \[PLT\-6896\] Add paging to system console log viewer · Issue \#6724 · mattermost/mattermost\-server](https://github.com/mattermost/mattermost-server/issues/6724)
> PLT-6896 Fix descriptions of `/logs`

- README.md
- v4/source/files.yaml
JIRA: https://mattermost.atlassian.net/browse/PLT-8278
Github: https://github.com/mattermost/mattermost-server/issues/7946
> [PLT-8278] Add a custom example to API reference for how to upload a file via the API

- v4/source/definitions.yaml
- v4/source/users.yaml
Let me know if you think it needs more or anything.
> ABC-24: add user auth put endpoint

- v4/source/emoji.yaml
mattermost/mattermost-server#8121
> ABC-100 Add sort query parameter to GET /emojis

- v4/source/emoji.yaml
Also fixed an error code for the standard emoji get endpoint.
> ABC-92 Add documentation for GET /emoji/name/{emoji_name} endpoint

- v4/source/system.yaml
https://mattermost.atlassian.net/browse/ABC-176
> ABC-176 Add note about updating enable uploads plugin setting

- v4/source/channels.yaml
See https://github.com/mattermost/mattermost-server/pull/8163
> ABC-79: Add channel autocomplete endpoint

- v4/source/system.yaml
Server PR: https://github.com/mattermost/mattermost-server/pull/8243
> PLT-8186 add documentation

- v4/source/teams.yaml
Team Icon API documentation.
https://github.com/mattermost/mattermost-server/issues/7616
https://github.com/mattermost/mattermost-server/pull/8284
https://github.com/mattermost/mattermost-redux/pull/403
https://github.com/mattermost/mattermost-webapp/pull/796
> PLT-7567: Integration of Team Icons 

- v4/source/introduction.yaml
This is the corresponding PR to https://github.com/mattermost/mattermost-server/pull/8371.
> MM-8604: document `config_changed` and `license_changed`

- v4/source/system.yaml
Server PR: https://github.com/mattermost/mattermost-server/pull/8453
update the doc to reflect the actual usage
> update doc for testEmail

- v4/source/system.yaml
The test s3 also expect the user to send the config. this update add the input needed
> update s3 test doc

- v4/source/introduction.yaml
In preparation for v4.9 release. APIv3 deprecation banner design is queued here https://mattermost.atlassian.net/browse/MM-9738
> Proposed changes to APIv3 deprecation section

- v4/source/channels.yaml
Add docs for /channels/{channel_id}/convert
> [GH-7775] Add docs for /channels/{channel_id}/convert

- v4/source/teams.yaml
Docs for new API endpoint to update a team's scheme.
> MM-10182: Adds docs for update team scheme endpoint.

- v4/source/teams.yaml
- v4/source/users.yaml
It is the documentation for the Ticket [MM-9779](https://mattermost.atlassian.net/browse/MM-9779) in the PR mattermost/mattermost-server#8604
> MM-9779: Add api documentation changes for avoid re-join on invitations feature

- v4/source/channels.yaml
Update permission of converting a channel from public to private to allow team admin
Server PR ~~to follow~~ - https://github.com/mattermost/mattermost-server/pull/8723.
> [MM-10433] Update permission of converting a channel from public to private to allow team admin

- v4/source/introduction.yaml
I've asked a few people in our team less familiar with upcoming API changes, as well as a few people in the community, to review our API deprecation section.
This PR updates the section based on feedback and suggestions received from @amyblais, @cpanato, @wget, @lindy65 and @lindalumitchell.
> Update API deprecation notice based on user feedback

- v4/source/schemes.yaml
- v4/source/teams.yaml
Fixes minimum version of `schemes` API to 5.0.
> Add permissions to get endpoint and increase versions to 5.0

- v4/source/definitions.yaml
https://mattermost.atlassian.net/browse/MM-10605
> MM-10605 Add int64 format to timestamps

- v4/source/introduction.yaml
> Adds link to WIP Postman documentation.

- v4/source/channels.yaml
See https://github.com/mattermost/mattermost-server/pull/9054.
> MM-1118: document inability to delete direct and group message channels

- v4/source/users.yaml
Based on question here https://pre-release.mattermost.com/core/pl/rkh7fumkoifcddspxa47igzu4e
> Update users.yaml 

- Makefile
- v4/source/reactions.yaml
Fix contents of reactions API
Reported here: https://pre-release.mattermost.com/core/pl/689bsj1q6pd458iorqnhwrkzqa
> Fix contents of reactions API

- v4/source/brand.yaml
Hi folks.
In that PR I add documentation related to https://github.com/mattermost/mattermost-server/pull/9552.
Cheers !
> Add documentation for the delete brand image action

- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/system.yaml
Remove all things WebRTC. Complements https://github.com/mattermost/mattermost-webapp/pull/1907 and https://github.com/mattermost/mattermost-server/pull/9700.
> MM-12505: Remove all things WebRTC

- v4/source/channels.yaml
- v4/source/definitions.yaml
webapp: https://github.com/mattermost/mattermost-webapp/pull/1607
redux: https://github.com/mattermost/mattermost-redux/pull/612
server: https://github.com/mattermost/mattermost-server/pull/9286
also fix one issue
> add channeltimezone api

- v4/source/definitions.yaml
- v4/source/users.yaml
Added API docs for GetUserTermsOfService API
> Added API docs for GetUserTermsOfService API

- v4/source/users.yaml
It would be good for someone to verify my changes are technically accurate.
Credit to @xcompass for bringing this to our attention 👍
> Add auth_data and auth_service fields to POST /users API call

- v4/source/definitions.yaml
- v4/source/users.yaml
New api endpoint was added to get the count of all system users.
https://github.com/mattermost/mattermost-server/pull/8847
> /users/stats api endpoint documentation.

- v4/source/definitions.yaml
https://mattermost.atlassian.net/browse/MM-12761
> MM-12761 Add post metadata documentation

- v4/source/users.yaml
Instead of just sanitizing the user's email address when using this route, we're going to completely prevent the user from using it if they can't see emails because of privacy settings.
https://mattermost.atlassian.net/browse/MM-13512
> MM-13512 Prevent getting a user by email based on privacy settings

- v4/source/files.yaml
- v4/source/posts.yaml
These are based on report here https://github.com/mattermost/mattermost-server/issues/10023
> Text updates for existing APIs

- v4/source/introduction.yaml
- v4/source/opengraph.yaml
in https://api.mattermost.com, some contents is missing. This PR will add these contents.
- OAuth section was found but no endpoint shows.
- Terms of Service section is not found.
- Integration action section is not found.
> Add missing sections

- v4/source/posts.yaml
Follow up on https://github.com/mattermost/mattermost-developer-documentation/issues/250
> Add code sample for ephemeral post endpoint

- Makefile
- v4/source/definitions.yaml
- v4/source/groups.yaml
- v4/source/introduction.yaml
Link to [the server PR](https://github.com/mattermost/mattermost-server/pull/10502).
[MM-14645](https://mattermost.atlassian.net/browse/MM-14645) and [MM-14646](https://mattermost.atlassian.net/browse/MM-14646)
> Add documentation for get groups by channel and teams endpoints

- v4/source/plugins.yaml
See https://github.com/mattermost/mattermost-api-reference/pull/407#issuecomment-479311541
cc @kaakaa
> Fix plugin route

- v4/source/definitions.yaml
- v4/source/users.yaml
Updated API docs to include TOS fields being included in certain user APIs
> Updated API docs to include TOS fields being included in certain user APIs

- v4/source/saml.yaml
This change complements https://github.com/mattermost/mattermost-server/pull/10341.
> MM-14294: update API to reflect hard-coded SAML certificate names

- v4/source/plugins.yaml
Solves ticket : [MM-15105](https://mattermost.atlassian.net/browse/MM-15105)
Fixes https://github.com/mattermost/mattermost-server/issues/10609
> [MM-15105] Add Go code samples to API reference for plugin endpoints

- v4/source/files.yaml
See https://github.com/mattermost/mattermost-server/blob/master/api4/file.go#L60
> /files/{file_id}/link requires authentication

- v4/source/users.yaml
See https://github.com/mattermost/mattermost-server/blob/master/api4/user.go#L26
> /users/stats requires authentication

- v4/source/users.yaml
Solves ticket [MM-8737](https://mattermost.atlassian.net/browse/MM-8737)
Fixes https://github.com/mattermost/mattermost-server/issues/10606
> [MM-8737] Add Go code samples to API reference for user endpoints

- v4/source/files.yaml
Solves ticket [MM-15106](https://mattermost.atlassian.net/browse/MM-15106)
Fixes https://github.com/mattermost/mattermost-server/issues/10607
> [MM-15106] Add Go code samples to API reference for file endpoints

- v4/source/teams.yaml
Solves ticket : [MM-15104](https://mattermost.atlassian.net/browse/MM-15104)
Fixes https://github.com/mattermost/mattermost-server/issues/10608
> [MM-15104] Add Go code samples to API reference for team endpoints

- Makefile
- v4/source/bots.yaml
- v4/source/definitions.yaml
- v4/source/introduction.yaml
Replaces: https://github.com/mattermost/mattermost-api-reference/pull/449
> MM-16067 Docs for bot APIs

- v4/source/users.yaml
Adds documentation for the new API parameter added in https://github.com/mattermost/mattermost-server/pull/11406
https://mattermost.atlassian.net/browse/MM-16477
> MM-16477 Add since parameter to /api/v4/users/ids

- v4/source/channels.yaml
https://mattermost.atlassian.net/browse/MM-17194
- [Server PR](https://github.com/mattermost/mattermost-server/pull/11706)
> [MM-17194] Document the case for channel search where the user don't have the list_team_channels permission

- .circleci/config.yml
- build/Jenkinsfile.master
- build/Jenkinsfile.pr
Add circleci and deprecate the jenkins file
> add circleci

- v4/source/definitions.yaml
- v4/source/posts.yaml
Add docs for GET '/users/{user_id}/channels/{channel_id}/posts/unread'
Server PR - https://github.com/mattermost/mattermost-server/pull/11486
> MM-11210 Add docs for GET '/users/{user_id}/channels/{channel_id}/posts/unread'

- v4/source/users.yaml
Docs for https://github.com/mattermost/mattermost-server/pull/11200
Related Jira ticket: [MM-7854](https://mattermost.atlassian.net/browse/MM-7854)
> [MM-7854] revoke sessions from all users

- v4/source/teams.yaml
Adds docs for new query param added in https://github.com/mattermost/mattermost-server/pull/11325.
> Adds include_total_count query param.

- v4/source/oauth.yaml
- v4/source/plugins.yaml
- v4/source/teams.yaml
Update old repo name on sample code from platform to mattermost-server
> Update old repo name on sample code from platform to mattermost-server

- v4/source/definitions.yaml
- v4/source/posts.yaml
Added docs for setting a channel as unread from a given post
Jira ticket: [MM-17070](https://mattermost.atlassian.net/browse/MM-17070)
> [MM-17070] add set-unread to posts

- v4/source/system.yaml
Added docs for new endpoint to test a SiteURL.
Requires https://github.com/mattermost/mattermost-server/pull/11944 to be merged
Jira ticket: https://mattermost.atlassian.net/browse/MM-14521
> Added SiteURL test endpoint

- v4/source/users.yaml
Fixed a couple of problems with go code samples related to `User` API.
> Fix failing go code in user API samples

- v4/source/definitions.yaml
- v4/source/groups.yaml
Regarding https://mattermost.atlassian.net/browse/MM-13155
> [MM-13155] Finished documentation for the group endpoints

- v4/source/groups.yaml
Updates documentation to match the changes made in https://github.com/mattermost/mattermost-server/pull/12961 .
> [MM-19778] Update groups documentation to match changes for GET /groups

- v4/source/channels.yaml
- v4/source/teams.yaml
For the changes made in:
* https://github.com/mattermost/mattermost-server/pull/12830
* https://github.com/mattermost/mattermost-server/pull/12910
> Adds docs for channel search.

- v4/source/plugins.yaml
See https://github.com/mattermost/mattermost-server/pull/12983.
> document 404 when deleting plugins

- v4/source/teams.yaml
Related PRs:
https://github.com/mattermost/mattermost-server/pull/13372
https://github.com/mattermost/mattermost-webapp/pull/4495
https://github.com/mattermost/mattermost-redux/pull/1010
> updated  '/teams/{team_id}/members/batch'

- v4/source/system.yaml
Adds documentation for config patch endpoint: [issue](https://github.com/mattermost/mattermost-server/issues/MM-19720)
https://github.com/mattermost/mattermost-server/issues/12958
> [MM-19720] Add documentation for config patch endpoint

- v4/source/commands.yaml
This PR provides documentation for two new endpoints:
1. retrieve slash command by id
2. move slash command to another team
https://mattermost.atlassian.net/browse/MM-19250
https://mattermost.atlassian.net/browse/MM-21727
> MM-19250 - documentation for new endpoint to retrieve command by id

- v4/source/definitions.yaml
- v4/source/system.yaml
This pull-request provides endpoint documentation for PR https://github.com/mattermost/mattermost-server/pull/13212
> MM-8607 - document serverbusy endpoints

- v4/source/introduction.yaml
This PR fixes a simple typo.
No ticket.
> fixed typo: interating -> interacting

- v4/source/definitions.yaml
- v4/source/plugins.yaml
Add marketplace plugin API documentation.
`page`, `per_page`, and `server_version` params on GET method is not yet implemented, please kindly check.
Fixes https://github.com/mattermost/mattermost-server/issues/13899
> MM-22616 - Add marketplace plugin docs

- v4/source/teams.yaml
This PR provides API docs for new server endpoint ` /teams/{team_id}/privacy`
Server PR:  https://github.com/mattermost/mattermost-server/pull/14287
https://mattermost.atlassian.net/browse/MM-23722
> MM-23722  docs for /teams/{team_id}/privacy

- v4/source/teams.yaml
This PR provides docs for new restore team endpoint.
https://mattermost.atlassian.net/browse/MM-23724
> API docs for RestoreTeam

- v4/source/bots.yaml
- v4/source/brand.yaml
- v4/source/channels.yaml
- v4/source/commands.yaml
- v4/source/files.yaml
- v4/source/oauth.yaml
- v4/source/plugins.yaml
- v4/source/roles.yaml
- v4/source/schemes.yaml
- v4/source/system.yaml
- v4/source/teams.yaml
- v4/source/users.yaml
replaced invalid paths
https://mattermost.atlassian.net/browse/MM-24438
> MM-24438 Update mattermost-server import path in API docs golang code examples

- v4/source/users.yaml
This PR adds documentation for new `/users/{user_id}/verify` endpoint.
https://mattermost.atlassian.net/browse/MM-23721
> [MM-23721] Add docs for new verify user endpoint

- Makefile
- v4/source/bleve.yaml
- v4/source/introduction.yaml
Adds documentation to the Bleve purge indexes endpoint
https://mattermost.atlassian.net/browse/MM-20979
- [Has server PR](https://github.com/mattermost/mattermost-server/pull/14562)
- [Has enterprise PR](https://github.com/mattermost/enterprise/pull/653)
- [Has webapp PR](https://github.com/mattermost/mattermost-webapp/pull/5120)
> [MM-20979] Add bleve purge indexes endpoint

- v4/source/commands.yaml
- v4/source/definitions.yaml
This PR will add autocomplete_suggestions endpoint doc
Fixes https://mattermost.atlassian.net/browse/MM-21493
> [MM-20684] Slash command autocomplete

- v4/source/users.yaml
API changes to complement https://github.com/mattermost/mattermost-server/pull/14331.
https://mattermost.atlassian.net/browse/MM-18756
> document /api/v4/users/<user_id>/typing event

- v4/source/channels.yaml
This PR adds move channel documentation for the new `/channels/{channel_id}/move` endpoint.
https://mattermost.atlassian.net/browse/MM-23719
> [MM-23719] Add move channel documentation

- v4/source/channels.yaml
Update to get channels endpoint done in https://github.com/mattermost/mattermost-server/pull/14721.
https://mattermost.atlassian.net/browse/MM-25261
> MM-25261: get channels endpoint.

- v4/source/channels.yaml
This PR reflects the changes in the https://github.com/mattermost/mattermost-server/pull/14887
https://mattermost.atlassian.net/browse/MM-21464
> [MM-21464] channels/move: reflect changes in the api

- v4/source/ldap.yaml
Add docs for the change in https://github.com/mattermost/mattermost-server/pull/14794
https://mattermost.atlassian.net/browse/MM-25651
> [MM-25651] ldap/migrteid: add docs

- v4/source/bots.yaml
- v4/source/users.yaml
Reflects the changes in https://github.com/mattermost/mattermost-server/pull/14877
https://mattermost.atlassian.net/browse/MM-25648
> [MM-25648] bots/users: add docs for conversions

- v4/source/users.yaml
https://mattermost.atlassian.net/browse/MM-25646
- [Has server changes](https://github.com/mattermost/mattermost-server/pull/14903)
- [Has mmctl changes](https://github.com/mattermost/mmctl/pull/170)
> [MM-25646] Adds documentation for the permanent delete all users local endpoint

- v4/source/users.yaml
https://mattermost.atlassian.net/browse/MM-26532
https://github.com/mattermost/mattermost-server/pull/14923
https://github.com/mattermost/mattermost-webapp/pull/5798
> [MM-26532] Add active, inactive, and role params to GET /users route

- v4/source/system.yaml
This PR reflects the changes in https://github.com/mattermost/mattermost-server/pull/14928
https://mattermost.atlassian.net/browse/MM-25657
> [MM-25657] system: add docs for config migration

- v4/source/channels.yaml
Document list private channels endpoint 
https://mattermost.atlassian.net/browse/MM-26539
Required by: https://mattermost.atlassian.net/browse/MM-23596
> MM-26539/MM-23596: Document list private channels endpoint

- v4/source/users.yaml
https://mattermost.atlassian.net/browse/MM-16696
> MM-16696: Add a note that userId can also be "me"

- v4/source/system.yaml
Adds OpenAPI signatures for the newly added API methods to support the admin warning system for metrics.
https://mattermost.atlassian.net/browse/MM-25042
> Add OpenAPI signatures for warning system for metrics API calls

- v4/source/channels.yaml
- Adds docs for newly added channel filters
- https://mattermost.atlassian.net/browse/MM-25990
- https://github.com/mattermost/mattermost-server/pull/15009
> [MM-25990] Add docs for newly added channel search filters

- v4/source/teams.yaml
- Adds filter options for team search, and removes `term` as a required parameter
- https://mattermost.atlassian.net/browse/MM-26969
> [MM-26969] Add filters to team search

- v4/source/channels.yaml
Added the last_delete_at parameter which will filter archived channels
by that timestamp
> MM-25563: update channelsForTeamForUser endpoint

- v4/source/teams.yaml
> Add missing parameter to "Add user to team" PHP code sample

- v4/source/channels.yaml
- This endpoint had an incorrect documented minimum version, this fixes that
- https://mattermost.atlassian.net/browse/MM-27522
> [MM-27522] Update channel moderation minimum version

- v4/source/teams.yaml
https://mattermost.atlassian.net/browse/MM-27507
> MM-25707: Document email invite rate limits

- v4/source/definitions.yaml
Just fixing a typo in one of the types.
> Rename deleted_at to delete_at

- v4/source/system.yaml
- v4/source/users.yaml
Docs for the changes in https://github.com/mattermost/mattermost-server/pull/14966
> [MM-25645] Add migrate_auth endpoint docs

- v4/source/users.yaml
This PR includes the reference for the new `/users/login/cws` endpoint
https://mattermost.atlassian.net/browse/MM-28083
> Login CWS doc

- v4/source/channels.yaml
- Updates permission requirements for converting a channel privacy
- Related server https://github.com/mattermost/mattermost-server/pull/15370
https://mattermost.atlassian.net/browse/MM-27274
> [MM-27274] Update channel privacy docs

- v4/source/definitions.yaml
- v4/source/system.yaml
> Notices API

- v4/source/bleve.yaml
- v4/source/saml.yaml
- v4/source/teams.yaml
- These endpoints are no longer exclusive to system_admins
- See related server PR https://github.com/mattermost/mattermost-server/pull/15558
- https://mattermost.atlassian.net/browse/MM-28536
- https://mattermost.atlassian.net/browse/MM-28535
> [MM-28536] [MM-28535] Change manage_system to write_auth where required 

- Makefile
- v4/source/cloud.yaml
- v4/source/definitions.yaml
- v4/source/introduction.yaml
Added entry for initial Cloud api endpoints that include:
- GET `/cloud/products`
- POST `/cloud/payment/`
- POST /cloud/payment/confirm
Server: https://github.com/mattermost/mattermost-server/pull/15428
[MM-27147](https://mattermost.atlassian.net/browse/MM-27147)
> MM-27147 - Added entry for Cloud api

- v4/source/cloud.yaml
- v4/source/definitions.yaml
`GetSubscription()` endpoint documentation
https://mattermost.atlassian.net/browse/MM-28211
> [MM-28211] Added GetSubscription endpoint

- v4/source/channels.yaml
- Document permanent delete of channel
- https://mattermost.atlassian.net/browse/MM-25659
> [MM-25659] document permanent delete of channel

- v4/source/users.yaml
- document permanent delete of user. 
- Part of https://mattermost.atlassian.net/browse/MM-25647
> [MM-25647] document permanent delete of user

- v4/source/cloud.yaml
API reference update for the endpoints to update company information.
https://mattermost.atlassian.net/browse/MM-28218
> [MM-28218] API reference for updating cloud customer information

- v4/source/cloud.yaml
- v4/source/definitions.yaml
This PR the new cloud endpoints docs for invoices
https://mattermost.atlassian.net/browse/MM-29157
> [MM-29157] Invoices endpoints for cloud

- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/users.yaml
Collapsed thread APIs. Server PR: https://github.com/mattermost/mattermost-server/pull/16091
https://mattermost.atlassian.net/browse/MM-29987
> MM-29987 Collapsed threads api

- v4/source/cloud.yaml
Added entry for cloud API endpoint `POST /cloud/webhook`
https://mattermost.atlassian.net/browse/MM-29845
> [MM-29845] Add spec for /cloud/webhook

- v4/source/users.yaml
Updated endpoints to include team id
> MM-30558 - updated routes for thread related APIs

- v4/source/users.yaml
> MM-30558 - updated routes for thread related APIs (#590)

- v4/source/definitions.yaml
- v4/source/system.yaml
Doc for the new license renewal link endpoint
https://mattermost.atlassian.net/browse/MM-30539
> [MM-30539] License renewal link endpoint

- v4/source/introduction.yaml
* Fix 404 link for js websocket client
N/A
> fix invalid link for js websocket client

- package-lock.json
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/system.yaml
- v4/source/users.yaml
- v4/source/webhooks.yaml
PR for the release of cloud
https://mattermost.atlassian.net/browse/MM-32168
> [MM-32168] Cloud release 2021-01-19

- Makefile
- v4/source/exports.yaml
- v4/source/introduction.yaml
PR adds `/exports` API endpoint to list/download/delete export files.
https://mattermost.atlassian.net/browse/MM-31249
> [MM-31249] Add exports endpoint

- v4/source/users.yaml
https://mattermost.atlassian.net/browse/MM-31713
> MM-31713 added getUserThread method

- Makefile
- v4/source/definitions.yaml
- v4/source/exports.yaml
- v4/source/introduction.yaml
- v4/source/users.yaml
The cloud release branch for 2021-02-10
https://mattermost.atlassian.net/browse/MM-32488
> [MM-32488] Cloud release 2021-02-10

- v4/source/users.yaml
documented "/users/{user_id}/teams/{team_id}/threads/mention_counts"
https://mattermost.atlassian.net/browse/MM-32525
> added GetThreadMentionsForUserPerChannel

- v4/source/status.yaml
- Added API documentation for custom status APIs
Server PR - https://github.com/mattermost/mattermost-server/pull/16835
> Custom status feature

- v4/source/cloud.yaml
Fix for the merged PR MM-32543
> Fix cloud limitreached docs

- v4/source/cloud.yaml
- v4/source/definitions.yaml
- v4/source/exports.yaml
- v4/source/status.yaml
- v4/source/system.yaml
- v4/source/users.yaml
This is the FF branch for the cloud release for Feb 24th 2021
https://mattermost.atlassian.net/browse/MM-32922
> [MM-32922] Cloud release for 20210224

- v4/source/cloud.yaml
Adds the spec for the ``` /cloud/subscription/limitreached/join```
[MM-32691](https://mattermost.atlassian.net/browse/MM-32691?atlOrigin=eyJpIjoiYmU1ZjdiMWJlZDRiNGE5ZmJjNGNjYjA2Y2VjZjA5YTEiLCJwIjoiaiJ9)
> [MM-32691] - Send email when the users are not able to join a workspace

- v4/source/cloud.yaml
- v4/source/definitions.yaml
- v4/source/files.yaml
https://mattermost.atlassian.net/browse/MM-33366
> [MM-33366] Cloud release 20210301

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/sharedchannels.yaml
Cloud release branch for 2021-03-15
https://mattermost.atlassian.net/browse/MM-33820
> [MM-33820] Cloud release 2021-03-15

- v4/source/definitions.yaml
- v4/source/plugins.yaml
- v4/source/sharedchannels.yaml
- v4/source/system.yaml
> Cloud merge 2021-03-30

- v4/source/saml.yaml
This PR adds documentation for the API endpoints which resets SAML users' AuthData field to their email.
https://mattermost.atlassian.net/browse/MM-32044
https://github.com/mattermost/mattermost-server/pull/17161
> [MM-32044] Reset SAML auth data

- Makefile
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/plugins.yaml
- v4/source/sharedchannels.yaml
- v4/source/system.yaml
Cloud FF from master to cloud for 2021-04-12
https://mattermost.atlassian.net/browse/MM-34757
> [MM-34757] Cloud FF 2021-04-12

- v4/source/introduction.yaml
https://mattermost.atlassian.net/wiki/spaces/Threads/pages/1751023686/Backend+implementation
Adds list of new websocket events part of the collapsed reply threads effort.
Ad hoc
> Added new websocket events, part of collapsed reply threads.

- v4/source/status.yaml
- Changed the request type to POST for the remove recent custom status API
- https://github.com/mattermost/mattermost-redux/pull/1409
- https://github.com/mattermost/mattermost-server/pull/17122
> Changed the method of delete recent custom status API to POST

- Makefile
- v4/source/introduction.yaml
- v4/source/permissions.yaml
Adds a new endpoint to retrieve ancillary permissions for corresponding section permission.
https://mattermost.atlassian.net/browse/MM-34838
Required for https://github.com/mattermost/mattermost-server/pull/17466
> [MM-34838] Remove Ancillary Permissions That Are Purposefully Being Remove

- Makefile
- v4/source/channels.yaml
- v4/source/dataretention.yaml
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/permissions.yaml
- v4/source/saml.yaml
- v4/source/status.yaml
- v4/source/teams.yaml
- v4/source/users.yaml
FF PR from master to cloud for Release in 5th of may
https://mattermost.atlassian.net/browse/MM-35170
> [MM-35170] Cloud release 2021-04-26

- v4/source/status.yaml
Server PR: mattermost/mattermost-server#16067
> add dnd_end_time in requestBody of updateStatus

- v4/source/status.yaml
This reverts commit 3d898faea72c448e89d088a26e1b870722f9d7d9.
https://github.com/mattermost/mattermost-server/issues/15640
> Revert "add dnd_end_time in requestBody of updateStatus (#629)"

- v4/source/definitions.yaml
- v4/source/status.yaml
https://mattermost.atlassian.net/browse/MM-35960
> [MM-35960] Cloud 2021-05-24

- v4/source/system.yaml
Added API doc for fetching last trial license
https://mattermost.atlassian.net/browse/MM-34437
> MM-34437 Added API docs for new prev trial license fetching API

- v4/source/status.yaml
Reverts mattermost/mattermost-api-reference#641
> add dnd_end_time in requestBody of updateStatus (#629)

- v4/source/status.yaml
- v4/source/system.yaml
> [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-06-21

- v4/source/status.yaml
Modified documentation for custom status APIs adding expiry support
https://github.com/mattermost/mattermost-server/pull/17570
> Custom status expiry

- v4/source/roles.yaml
This pull request adds api reference for newly created endpoint for listing all existing roles. 
https://github.com/mattermost/mattermost-server/issues/16972
> MM-32396 Add api reference for new roles endpoint

- v4/source/roles.yaml
> [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-07-06

- v4/source/definitions.yaml
> [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-09-20

- v4/source/channels.yaml
- v4/source/definitions.yaml
- v4/source/users.yaml
> [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-11-01

- v4/source/posts.yaml
New endpoint to fetch posts by a list of ids
https://mattermost.atlassian.net/browse/MM-38239
> docs for getPostsByIds

- v4/source/system.yaml
https://mattermost.atlassian.net/browse/MM-41184
> MM-41184: Remove the config migrate endpoint

- v4/source/introduction.yaml
xRef from: https://github.com/mattermost/mattermost-server/pull/19128
> Add a note on binary websocket messages

- v4/source/groups.yaml
New API endpoint docs.
https://mattermost.atlassian.net/browse/MM-40042
Related PR: https://github.com/mattermost/mattermost-server/pull/18839
> Added docs for 4 new endpoints related to custom groups.

- v4/source/channels.yaml
Some confusion came up with a customer about the term soft delete. This means archived within the UI, so changing the lanquage to match what the customer would experience.
> Update delete channel description.

- v4/source/groups.yaml
- v4/source/teams.yaml
- v4/source/users.yaml
Adding missing GET parameters on /groups /teams /users endpoints
[MM-41679](https://mattermost.atlassian.net/browse/MM-41679)
> [MM-41679] Adding missing parameters

- v4/source/posts.yaml
Adds missing parameters for /users/{user_id}/channels/{channel_id}/posts/unread : skipFetchThreads, collapsedThreads, collapsedThreadsExtended
- Part of https://mattermost.atlassian.net/browse/MM-35572
> [MM-35572] Add missing params paramsGetPostsAroundLastUnread

- v4/source/definitions.yaml
- v4/source/system.yaml
Update ping to add push notification test definition
None
https://github.com/mattermost/mattermost-server/pull/19610
> Update ping to add push notification test definition

- v4/source/plugins.yaml
Docs for https://github.com/mattermost/mattermost-server/pull/19613
https://mattermost.atlassian.net/browse/MM-41981
> [MM-41981] Always install the latest compatible version via the Marketplace

- v4/source/saml.yaml
Adds missing documentation for request body.
https://github.com/mattermost/mattermost-api-reference/issues/655
> Adds missing request body documentation.

- v4/source/definitions.yaml
- v4/source/reactions.yaml
Adds documentation for the top reactions for team/user endpoint. This endpoint is currently hidden behind a feature flag.
**See server PR for additional context:**
- https://github.com/mattermost/mattermost-server/pull/19850
Fixes https://mattermost.atlassian.net/browse/MM-42742
> [MM-42742] Top Reactions Documentation

- Makefile
- v4/source/cloud.yaml
- v4/source/definitions.yaml
- v4/source/introduction.yaml
- v4/source/usage.yaml
Add the API endpoint that returns the current usage limits for messages
JIRA - https://mattermost.atlassian.net/browse/MM-43917
- Has server changes https://github.com/mattermost/mattermost-server/pull/20152
> [MM-43917] Cloud Freemium limits API: messages/posts

- v4/source/posts.yaml
Added documentation for new 'include_deleted' query param on ```GetPost``` api.
Fixes https://github.com/mattermost/mattermost-server/issues/19867
JIRA: https://mattermost.atlassian.net/browse/MM-42192
> [MM-42192] Documentation for getting deleted posts

- v4/source/introduction.yaml
> Fix App Directory Link

- v4/source/emoji.yaml
Reverts mattermost/mattermost-api-reference#704
> Revert "Mm-20223 Add webp emoji support"

- v4/source/definitions.yaml
- v4/source/usage.yaml
- Add doc for the storage usage API endpoint
- Part of https://mattermost.atlassian.net/browse/MM-43918
> MM-43918: API for storage usage

- Makefile
More context here https://community.mattermost.com/core/pl/3ygwb8sj6t83dpchqcitz53geh
Fixes https://github.com/mattermost/mattermost-api-reference/issues/709
> Remove `--cdn` flag to circumvent redoc breaking changes

- v4/source/posts.yaml
- API documentation for post reminders
- N/A
> Post Reminders API Docs

- v4/source/definitions.yaml
- v4/source/insights.yaml
Documents the new `GET api/v4/teams/:team_id/top/team_members` API endpoint.
https://mattermost.atlassian.net/browse/MM-45120
https://github.com/mattermost/mattermost-server/pull/20708
> MM-45120: Documents the new api/v4/teams/:team_id/top/team_members API.

- v4/source/definitions.yaml
Changed spurious bool to string.
> Fix ChannelNotifyProps schema

- v4/source/definitions.yaml
- v4/source/insights.yaml
Documents the  following GET API endpoints.
- `api/v4/teams/:team_id:/top/threads` 
- `api/v4/users/me/top/threads` 
- `api/v4/users/me/top/dms` 
https://mattermost.atlassian.net/browse/MM-46502
https://github.com/mattermost/mattermost-server/pull/20195
https://github.com/mattermost/mattermost-server/pull/20690
> [MM-46502] Add API docs for top dms, top threads

- v4/source/system.yaml
Add documentation regarding put replacing the object instead of recursively changing it.
Fixes https://github.com/mattermost/mattermost-server/issues/20584
> plugin-config-patch-update

- v4/source/commands.yaml
API documentation correction, closes #5992
https://github.com/mattermost/docs/issues/5992
> Apply abandoned API documentation correction #5992 

- v4/source/users.yaml
Add `sort=display_name` to `GET /users`  doc as added in https://github.com/mattermost/mattermost-server/pull/21775/files.
https://mattermost.atlassian.net/browse/MM-49351
> MM-49351: Add sort options to be used with 'in_group' query parameter
